# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/alexrudd/cognito-srp"

[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "0.6.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/flosch/pongo2"
  version = "3.0.0"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/static"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/googollee/go-socket.io"

[[constraint]]
  branch = "master"
  name = "github.com/hpcloud/tail"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/service"

[[constraint]]
  name = "github.com/levigross/grequests"
  version = "0.10.0"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.3.2"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.11"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.8.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/HouzuoGuo/tiedot"
  version = "3.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/fatihkahveci/gin-inspector"

[[constraint]]
  name = "gopkg.in/appleboy/gin-status-api.v1"
  version = "1.0.1"
